### ISSUE TITLE
Video duration from playlist

### ISSUE THREAD

**Issue by Spimy** [jasonhaxstuff/popyt#138]
`video.minutes` and `video.seconds` are undefined when fetching videos from a playlist so I have to use `getVideo()` using the fetched videos to get the duration
![image](https://user-images.githubusercontent.com/34989646/85201305-73fc0900-b30f-11ea-8936-972992d3e6f8.png)

**Comment by jasonhaxstuff** [comment]
If you take a look at the [PlaylistItems overview](https://developers.google.com/youtube/v3/docs/playlistItems#resource-representation), you can see that it doesn't include the duration of the video. You must instead call `video.fetch()` or `youtube.getVideo(video)` in order to get the duration.

```js
{
  "kind": "youtube#playlistItem",
  "etag": etag,
  "id": string,
  "snippet": {
    "publishedAt": datetime,
    "channelId": string,
    "title": string,
    "description": string,
    "thumbnails": {
      (key): {
        "url": string,
        "width": unsigned integer,
        "height": unsigned integer
      }
    },
    "channelTitle": string,
    "playlistId": string,
    "position": unsigned integer,
    "resourceId": {
      "kind": string,
      "videoId": string,
    }
  },
  "contentDetails": {
    "videoId": string,
    "startAt": string,
    "endAt": string,
    "note": string,
    "videoPublishedAt": datetime
  },
  "status": {
    "privacyStatus": string
  }
}
```
