### ISSUE TITLE
Undefined LiveStatus for searchChannels

### ISSUE THREAD

**Issue by Raphilia** [jasonhaxstuff/popyt#165]
### What behaviour is expected:
A value of "live", "upcoming" or "false" according to the [docs](https://bbothell.me/popyt/docs/classes/channel.html#livestatus)

### What behaviour is observed:
A value of undefined is returned

### Steps/models to reproduce:
`let search = await youtube.searchChannels('PewDiePie', 1);
			console.log(search);`

**Outputs:**
`{
  results: [
    Channel {
      youtube: [YouTube],
      data: [Object],
      full: false,
      id: 'UC-lHJZR3Gqxm24_Vd_AJ5Yw',
      liveStatus: undefined,
      profilePictures: [Object],
      dateCreated: 2010-04-29T10:54:00.000Z,
      name: 'PewDiePie',
      about: 'I make videos.',
      url: 'https://youtube.com/channel/UC-lHJZR3Gqxm24_Vd_AJ5Yw'
    }
  ],
`
### Anything else:
I'm trying to make my Discord bot check whether a youtube channel is live or not, please tell me if I'm missing something as I'm a very new to programming myself.

**Comment by jasonhaxstuff** [comment]
This has been fixed in 563622e87bdf8130ae19939f8786d8b932632dea and is soon to be released in `v4.1.1`.
