### ISSUE TITLE
Length of video on playlist.fetchVideos()

### ISSUE THREAD

**Issue by johncovv** [jasonhaxstuff/popyt#69]
Would it be possible to add the length of the videos when we request a playlist? When I use `playlist.fetchVideos()`, it returns a lot of information, but the length of the videos doesn't come.

**Comment by jasonhaxstuff** [comment]
The lengths of the videos aren't returned in the [PlaylistItems](https://developers.google.com/youtube/v3/docs/playlistItems#contentDetails) response by the YouTube API. You'll just have to make an extra request for the length of the video for now.
