### ISSUE TITLE
Playlist class documentation broken

### ISSUE THREAD

**Issue by iComputer7** [jasonhaxstuff/popyt#72]
https://github.com/jasonhaxstuff/popyt/blob/e49236a888b24720868212aac3e794aa09a0cae6/docs/docs/classes/playlist.html#L228

Looks like a tag that wasn't escaped. It breaks the rest of the page and makes it not visible.

**Comment by jasonhaxstuff** [comment]
I assumed that typedoc would escape that for me. Guess I'll have to do it manually. Thanks for the issue!

**Comment by jasonhaxstuff** [comment]
Fixed by a3ad5e3
