### ISSUE TITLE
Support more search video options

### ISSUE THREAD

**Issue by ripern** [jasonhaxstuff/popyt#83]
Search currently supports these parameters: types, searchTerm, maxResult and pageToken
https://github.com/jasonhaxstuff/popyt/blob/master/src/index.ts#L90

Would be nice if it also supported these: eventType, fields, type, videoCategoryId and videoEmbeddable.
https://developers.google.com/youtube/v3/docs/search/list supports a number of other p
it

**Comment by jasonhaxstuff** [comment]
Thanks for contributing with your issue!
