### ISSUE TITLE
can't compile with TS on 3.1.0

### ISSUE THREAD

**Issue by iwa** [jasonhaxstuff/popyt#86]
each time I want to compile using the v3.1.0 of popyt, these errors appears :

![Screen Shot 2020-05-12 at 14 00 02](https://user-images.githubusercontent.com/19956672/81686586-e2b88d80-9458-11ea-803b-f84b208670cf.png)

**Comment by jasonhaxstuff** [comment]
Should be fixed with 2d22872 and in version 3.2.0 (releasing soon)

**Comment by jasonhaxstuff** [comment]
Published v3.2.0 @ https://www.npmjs.com/package/popyt/v/3.2.0
